// <auto-generated />
namespace YNoteWPF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addmanytomanyrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmanytomanyrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201910281055338_add-many-to-many-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
