// <auto-generated />
namespace YNoteWPF_DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201910280110284_addSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
